version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-riupotmgtu0b"
s3_prefix = "sam-app"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
